//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS031874v4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int Id { get; set; }
        public string Booking_date { get; set; }
        public string Shipping_date { get; set; }
        public string Destination { get; set; }
        public string Type { get; set; }
        public string Weight { get; set; }
        public string Ship_regnum { get; set; }
        public string Status { get; set; }
    }
}
